### ISSUE TITLE
When playing Reaper arrangement some MIDI items (with only one note) in Playtime get silenced after the first beat and the play normally when they loop for the second time.

### ISSUE THREAD

**Issue by atencion** [helgoboss/helgobox#1000]
**Describe the bug**
I have seveal midi items in Playtime slots.  These items are a single not that triggers a VST with samples. When playing Reaper arrangement some MIDI items in Playtime get silenced after the first beat and the play normally when they loop for the second time.

**To Reproduce**
1. Play Reaper Arrangement
2. PLaytime syncs and play some midi that have only one long midi note only play the first hit and then get silenced. 
3. Others that have several midi notes never play the first not, only from measures that are not the initial.
4. The second time they loop they all play OK.

**Expected behavior**
All midi clips should play from measure 1 and never get silenced.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
It happens with several VST, but this case im describing happens with Rando Sampler.

**Comment by helgoboss** [comment]
Context: Very likely related to PDC. Related to #968.

**Comment by atencion** [comment]
This happens also when Transport Syncronization in Playtime is in FULL mode.

**Comment by helgoboss** [comment]
This also needs to be fixed when playing ignited clips in Playtime itself.
