### ISSUE TITLE
With Launchpad X, right navigation button light get stuck on

### ISSUE THREAD

**Issue by TubularCorpration** [helgoboss/helgobox#1090]
When the number of columns in Playtime is increased to more than 8, the > button on the Launchpad X lights, but once lit it stays lit for the rest of the session regardless of whether it is contextually correct (however I didn't think to switch the LPX to note or custom mode when I encountered the bug last night and I don't have it with me now, so I don't know if the stuck light persists across mode changes).

**To Reproduce**
1. Start a fresh instance of Playtime 2 with the Launchpad X connected
2. Add a column.  The > button will light up.
3. (optional) Press the > button to scroll right.  The < button will light, and the > will remain lit. The pads will display the content of columns 2-9
4. (optional) Press < to scroll back to columns 1-8.  The < button will no longer be lit, the > will remain lit.
5. Remove a column so that the column count is 8 again.  The > button will stay lit.

**Expected behavior**
The > button should only be lit when it is possible to scroll up through the columns.  If the column count is 8 or less OR column 8 on the LPX grid is displaying the highest column in the Playtime session, it shouldn't be lit.  This is how the < button behaves.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - I don't have the exact build installed on my desktop available right now, but it is current.

**Comment by helgoboss** [comment]
Thanks for the report. It's an issue I'm aware about (on all controllers actually), but it didn't get priority yet.

**Comment by helgoboss** [comment]
There's a related issue: Scrolling down, deleting the last rows => Can't scroll up anymore. Also affects all controllers. Will look into it.
