### ISSUE TITLE
Playtime: Error "not implemented" when exporting to arrangement

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/helgobox#1098]
User reported:

I am not able to export tracks, matrix or sequences in arrangement view. The unknow error window shows up instead

--- cut ---
REAPER version:      7.20/x64
Module name:         Helgobox
Module version:      v2.16.1/x86_64 rev 59b056 (2024-08-09 10:39:55 UTC)
Module base address: 0x7ff85a950000
Module size:         0x2754000

Message: not implemented

   0:     0x7ff85bfb1cdb - invoke_host
   1:     0x7ff85bfaf9f2 - invoke_host
   2:     0x7ff85bf20aeb - invoke_host
   3:     0x7ff85c1bb0c7 - cpp_to_rust_ProjectStateContext_SetTempFlag
   4:     0x7ff85c1baf19 - cpp_to_rust_ProjectStateContext_SetTempFlag
   5:     0x7ff85c1b933f - cpp_to_rust_ProjectStateContext_SetTempFlag
   6:     0x7ff85c1bac08 - cpp_to_rust_ProjectStateContext_SetTempFlag
   7:     0x7ff85c4abb74 - cpp_to_rust_ProjectStateContext_SetTempFlag
   8:     0x7ff85c4abc3d - cpp_to_rust_ProjectStateContext_SetTempFlag
   9:     0x7ff85bdfce27 - invoke_host
  10:     0x7ff85bd39965 - invoke_host
  11:     0x7ff85bda3129 - invoke_host
  12:     0x7ff85bda2cad - invoke_host
  13:     0x7ff85b42ed73 - MAIN
  14:     0x7ff85affce2d - NSEEL_HOSTSTUB_LeaveMutex
  15:     0x7ff85b8d3d8a - invoke_host
  16:     0x7ff85b46539c - invoke_host
  17:     0x7ff85b20b353 - DllMain
  18:     0x7ff85bf489b3 - invoke_host
  19:     0x7ff85ae62cc6 - NSEEL_HOSTSTUB_LeaveMutex
  20:     0x7ff85c07f2ff - cpp_to_rust_ProjectStateContext_SetTempFlag
  21:     0x7ff85c061c83 - cpp_to_rust_IReaperControlSurface_Run
  22:        0x140330f0b - <unknown>
  23:        0x14020319b - <unknown>
  24:        0x1402028ca - <unknown>
  25:        0x1402020d3 - <unknown>
  26:        0x1404bcea1 - <unknown>
  27:     0x7ff8d2913170 - ScreenToClient
  28:     0x7ff8d2912912 - ScreenToClient
  29:     0x7ff8d295b859 - UnpackDDElParam
  30:     0x7ff8d290ef5c - CallWindowProcW
  31:     0x7ff8d290e684 - DispatchMessageW
  32:        0x1404b3dd0 - <unknown>
  33:        0x140aac661 - <unknown>
  34:     0x7ff8d2307374 - BaseThreadInitThunk
  35:     0x7ff8d3ddcc91 - RtlUserThreadStart
--- cut ---

**Comment by bvavra** [comment]
Just an FYI that I also experience this issue (and have already sent an email yesterday with details).  I've noticed this only impacts exporting MIDI; I can export audio clips just fine.
