### ISSUE TITLE
Playtime opens a white screen or no screen at all.

### ISSUE THREAD

**Issue by Lockheed22** [helgoboss/helgobox#1114]
Playtime won’t open correctly when opening an existing project and try to open playtime by button.
When there’s already multiple instances of realearn loaded in that project.

**Comment by helgoboss** [comment]
Hi, can't reproduce this here.

- Which OS?
- Which Helgobox version?
- Ideally, please attach a minimal project that reproduces the issue

**Comment by Lockheed22** [comment]
Windows 11
Reaper 7.20
Helgobox 2.16.1

**Comment by helgoboss** [comment]
Got an example project via email. Will try to reproduce on Windows (can't reproduce on macOS).

**Comment by helgoboss** [comment]
For the record, there was ongoing email communication about this. Couldn't reproduce this with the example project. The project was a bit complex with 10+ Helgobox instances.

However, we found a workaround: Open the Helgobox instance that contains Playtime and press Menu => Show app. 

Therefore I close this now. If there are more and more cases where this happens, anybody can comment and I can reopen it.

**Comment by Lockheed22** [comment]
Hey Benjamin,
Is there a way to control playtime pitch and tempo using a controller?
I’m really trying to make it function like a sampler but some features seem only to be controlled by mouse.
Greets Robin

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Benjamin Klum ***@***.***>
Verzonden: Monday, August 26, 2024 9:59:35 AM
Aan: helgoboss/helgobox ***@***.***>
CC: Lockheed22 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [helgoboss/helgobox] Playtime opens a white screen or no screen at all. (Issue #1114)


For the record, there was ongoing email communication about this. Couldn't reproduce this with the example project. The project was a bit complex with 10+ Helgobox instances.

However, we found a workaround: Open the Helgobox instance that contains Playtime and press Menu => Show app.

Therefore I close this now. If there are more and more cases where this happens, anybody can comment and I can reopen it.

**Comment by helgoboss** [comment]
Hi Robin, please create a feature request (discussion in the "Ideas" section).
