### ISSUE TITLE
Playtime: Also play ignited clips when starting just one clip in silence mode

### ISSUE THREAD

**Issue by atencion** [helgoboss/helgobox#1119]
**Describe the bug**
Pressing stop on a column makes all clips on tha column stop but then when strating to play a clip from that column again no other clips from other columns will play.

**To Reproduce**
1. HAve at least 2 playing clips in different columns and rows
2. While playing click on the Stop button from one of the columns. The clips in tha column stop and the other keep playing
3. press spacebar to stop playtime 
4. now press play on the clip that was stopped but the clip that was never stopped wont play.

**Expected behavior**
no clips should stop playing unless i specifically stop them either from it`s slot button , column button or other row is selected.

**Screenshots**
heres a video capture
https://drive.google.com/file/d/14Zfa9EtMZ9kcjeZ7nWoFYMGT5z2dLRgb/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by helgoboss** [comment]
This behavior is actually intended. The rationale behind it is:

- Pressing the *global* play button should play *all* ignited clips (ignited = the memorized ones with the round play button).
- Pressing a *specific* play button of a slot should play *only that* slot (if this is not desired, the user  should use the *global* play button).
- After pressing that *specific* play button, the ignited clips are still visible as ignited. The user can choose which of the ignited ones to start playing later and which not.
- In a future update, I want to add the ability to ignite clips manually while in silence mode, simply by pressing Cmd/Ctrl + the slot play button. **<== I think this is what you are looking for** In your case, you would have clicked the play button of the "83bpm" slot while holding Cmd/Ctrl. After that you press space and both clips would play.

**Comment by atencion** [comment]
oh i see. Well, I think that is very counterintuitive in my opinion. The overall implementation and behaviour of ableton, bitwig and other clip launchers for over 20 years. Muscle memory is very settled. hahah 

I`m not sure i really understand why this would be and intented behavour since pressing the global play button wouild keep me from coming back to the performance with that stopped clipped playing again since i cannot press play on both at the same time.  Having them in the same row could be a workaround but i guess that conditions the live performance so much to be free. 

TO be honest, i still dont understand that silence mode thing. Maybe it`s good to record at first and defined the project tempo recording for the first time, but still, maybe that should be a switch or something in the interface? 


> In a future update, I want to add the ability to ignite clips manually while in silence mode, simply by pressing Cmd/Ctrl + the slot play button. <== I think this is what you are looking for In your case, you would have clicked the play button of the "83bpm" slot while holding Cmd/Ctrl. After that you press space and both clips would play.

Maybe it could be the other way around? Use a modifier to only play that particular clip and silence the rest?

**Comment by helgoboss** [comment]
> oh i see. Well, I think that is very counterintuitive in my opinion. The overall implementation and behaviour of ableton, bitwig and other clip launchers for over 20 years. Muscle memory is very settled. hahah

Hmm, okay. I didn't check how it was in Live, until now. I find it interesting that I came up with almost the same solution as theirs, with only that slight detail different LOL. And of course with that double-click to stop abruptly, which Live doesn't seem to have.

That might indeed be a reason to change the behavior, to make it easier for the people coming from there.

> I`m not sure i really understand why this would be and intented behavour since pressing the global play button wouild keep me from coming back to the performance with that stopped clipped playing again since i cannot press play on both at the same time. Having them in the same row could be a workaround but i guess that conditions the live performance so much to be free.

This behavior was purely inspired by the analogy "single => single", "global => all". The problem that you described could be handled with that "manual igniting" feature, but I agree that it might be too much trouble in live situations.

Okay, I will change this. If someone doesn't want the other ignited clips to be played when playing a single clip, he can always double-click the matrix stop button before pressing the slot play button (which unignites all slots). The only downside is that he doesn't see the previously ignited slots anymore, but I guess that's acceptable.

> TO be honest, i still dont understand that silence mode thing. Maybe it`s good to record at first and defined the project tempo recording for the first time, but still, maybe that should be a switch or something in the interface?

Silence mode is basically just "Stopped", with the additional possibility to dictate a new tempo, in multiple ways:

- Count-in tempo tapping
- Changing tempo via tempo control
- Tempo-detection recording
 
The reason for automatically initiating a tempo-detection recording is that it saves buttons. Simply recording from stopped state, without any sort of count-in/pre-roll, occurred wild and unnecessary to me. Tempo-detection recording, by contrast, goes quite well with the "dictate new tempo" idea.

If some people really need recording from stopped state without tempo detection, I could still add that in the feature.

> > In a future update, I want to add the ability to ignite clips manually while in silence mode, simply by pressing Cmd/Ctrl + the slot play button. <== I think this is what you are looking for In your case, you would have clicked the play button of the "83bpm" slot while holding Cmd/Ctrl. After that you press space and both clips would play.
> 
> Maybe it could be the other way around? Use a modifier to only play that particular clip and silence the rest?

I guess that would work as well. Let me think about that.

**Comment by atencion** [comment]
> Hmm, okay. I didn't check how it was in Live, until now. I find it interesting that I came up with almost the same solution as theirs, with only that slight detail different LOL. And of course with that double-click to stop abruptly, which Live doesn't seem to have.
> 
> That might indeed be a reason to change the behavior, to make it easier for the people coming from there.

Great I`m glad you could see it. Sometimes it`s hard to explain exactly how the workflow feels.

> This behavior was purely inspired by the analogy "single => single", "global => all". The problem that you described could be handled with that "manual igniting" feature, but I agree that it might be too much trouble in live situations.
> 
> Okay, I will change this. If someone doesn't want the other ignited clips to be played when playing a single clip, he can always double-click the matrix stop button before pressing the slot play button (which unignites all slots). 

Super if you can change it!!  THANKS !!

> The only downside is that he doesn't see the previously ignited slots anymore, but I guess that's acceptable.

Yeah, but I don`t think that would be an issue cause would be an expected beahaviour to double click the matrix stop button to stop everything, so that basically is what a user would want. 

> Silence mode is basically just "Stopped", with the additional possibility to dictate a new tempo, in multiple ways:
> 
> * Count-in tempo tapping
> * Changing tempo via tempo control
> * Tempo-detection recording
> 
> The reason for automatically initiating a tempo-detection recording is that it saves buttons. Simply recording from stopped state, without any sort of count-in/pre-roll, occurred wild and unnecessary to me. Tempo-detection recording, by contrast, goes quite well with the "dictate new tempo" idea.
> 
> If some people really need recording from stopped state without tempo detection, I could still add that in the feature.

Yeah, please! Should i make a request for it?  Again, a count in is so important to get the feel and get ready before recording in a slot from a stopped state of playtime. I think again is the way ableton and bitwig work and again would really help people coming from there.  Maybe a count in / detect  switch or something like that so users can decide before playing in playtime? I don`t know, but maybe the same metronome on or off could be that. If metronome is on, you want a count in always...if it is off, then it detects tempo ? 

> 
> > > In a future update, I want to add the ability to ignite clips manually while in silence mode, simply by pressing Cmd/Ctrl + the slot play button. <== I think this is what you are looking for In your case, you would have clicked the play button of the "83bpm" slot while holding Cmd/Ctrl. After that you press space and both clips would play.
> > 
> > 
> > Maybe it could be the other way around? Use a modifier to only play that particular clip and silence the rest?
> 
> I guess that would work as well. Let me think about that.

Sure! If you need any ideas just let me know. THank yoU!

**Comment by atencion** [comment]
Here...settings Record, Count In (and tehre you specify the number of bars)
![image](https://github.com/user-attachments/assets/b28fcd05-82b0-4dfe-88a1-bdc5b8f93db5)

**Comment by helgoboss** [comment]
I adjusted the following feature request accordingly: https://github.com/helgoboss/helgobox/discussions/1010

**Comment by atencion** [comment]
Thank you!! That`s great

**Comment by helgoboss** [comment]
I changed the behavior for triggering ignited clips according to our discussion. Will be in 2.16.4.

**Comment by atencion** [comment]
Amazing!!!!!
THANK YOU!
