### ISSUE TITLE
Playtime: Enabling/disabling FX with PDC while REAPER is stopped totally destroys timing

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/helgobox#1164]
The following can be observed when having latency-heavy FX on the master FX chain. This issue is PDC-related.

Can easily be tested by putting ReaFir on the master track with a huge FFT size (e.g. 32768).

## Enabling/disabling such FX while just Playtime is playing, leads to loss of timing

This should ideally be fixed by using a form of resyncing (by tracking a hypothetical playback position).

#1180 is similar but is about the case that REAPER transport is running.

**Comment by jimmydeer** [comment]
Nice!



Kind regards,

*jimmy deer*
jimmydeer.com

  <https://www.instagram.com/jimmydeermusic/>
<https://www.facebook.com/JimmyDeerMusic/>

**Comment by helgoboss** [comment]
Hi Jimmy.

For now, this only fixes the issue while REAPER is stopped.

#1180 will take care of the case when REAPER is playing. This won't be part of the 2.16.4 release.

**Comment by jimmydeer** [comment]
Ok cool



Kind regards,

*jimmy deer*
jimmydeer.com

  <https://www.instagram.com/jimmydeermusic/>
<https://www.facebook.com/JimmyDeerMusic/>

**Comment by helgoboss** [comment]
Note: Timing issues can still occur. It just got a bit better than before. Might improve that in the future step by step. We will see what are the natural limits here. Changing PDC during a live session while things are still playing is not a good idea anyway, in no DAW. It will most likely lead to clicks and stuff.
