### ISSUE TITLE
Playtime doesn't work with MIDI input devices > ID 63

### ISSUE THREAD

**Issue by johnsamuelson** [helgoboss/helgobox#1165]
**Describe the bug**

To better control what and who is sending MIDI to Playtime for various loops, I would like to use a virtual MIDI port (Reaper Loopback 1 via MIDI Device List). It sets ok in the main arrange window but Playtime shows 'No input' and refuses to play ball

**To Reproduce**

1. Create Reaper Loopback MIDI port via MIDI Devices Preference page
2. Set as input in Playtime
3. See 'no input' instead of 'Reaper Loopback 1: Channel 1' which is what the main arrange page shows

**Expected behavior**

Should work as expected above

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Version [e.g. Ventura 13.6.7]
 
MacOS 12.6.1, Reaper v7.20

**Additional context**

**Comment by helgoboss** [comment]
Works here.

What if you close and reopen the Playtime window (or press the refresh button in the window title bar)? Maybe it just didn't get the information about the newly added loopback MIDI port.

**Comment by johnsamuelson** [comment]
Nope - I've tried closing Reaper too, tried the refresh button. Every time I set it to Reaper Loopback 1 it just defaults to 'none' as input and won't let me arm it. Very odd!
![Screenshot 2024-09-03 at 13 06 16](https://github.com/user-attachments/assets/c61949ab-3b48-43fb-bb8d-f0b21e51d292)

**Comment by helgoboss** [comment]
Which version of Helgobox?

**Comment by johnsamuelson** [comment]
Just updated it and nope no change! How odd. 

It's device number 64 (I've got a lot of MIDI flying about, plus a lot of redundant devices to be fair). Not enabled for Control messages but that shouldn't be an issue as neither are several other inputs which do work with Playtime..

**Comment by helgoboss** [comment]
Yes, it's a bug. Will be fixed in 2.16.4. Until then, you can use the mentioned workaround.
