### ISSUE TITLE
No count-in or pre-roll 

### ISSUE THREAD

**Issue by jimmydeer** [helgoboss/helgobox#1185]
**Describe the bug**
clicking on clip record button does not start the metronome for count-in or pre-roll

**To Reproduce**
1. start new project
2. add pt
3. select mixed
4. setup and enable metronome
5. check to make sure metronome count-in works with reaper by itself (it does)
6. press record on clip

what I expect: count-in
what happens: red circle blinks, playtime runs, no count in

 - OS: [e.g. macOS] osx ventura 13.6.3
 - Version [e.g. Ventura 13.6.7]

**Additional context**
![Screenshot 2024-09-11 at 4 25 14 AM](https://github.com/user-attachments/assets/adaa26b8-6b0f-47e6-a186-ff73fee5f278)

**Comment by helgoboss** [comment]
You need to enable the metronome on Playtime .

**Comment by jimmydeer** [comment]
Perfect, thanks
