### ISSUE TITLE
Metronome is doubled in 8/8 signature

### ISSUE THREAD

**Issue by aeantipov** [helgoboss/helgobox#1201]
**Describe the bug**
Playtime metronome shows exactly double the value in reaper.

**To Reproduce**
1. Go to Playtime
2. Tweak the metronome without any tempo markers present.
3. See error

**Expected behavior**
Same value in both.

**Screenshots**
![image](https://github.com/user-attachments/assets/1667f7fa-cc3a-46d2-983b-be21637b79fa)

**Desktop (please complete the following information):**
 - OS: Win11
 - Reaper 7.22, Playtime 2.16.8

**Additional context**
I followed the instruction inside of playtime on editing metronome and there the click rate of the source is also doubled, so might not be a playtime issue per se.
The tempo is 8/8. 
![image](https://github.com/user-attachments/assets/4fceb1d8-0591-4b5f-8fe7-8ebc2b4edf08)

**Comment by helgoboss** [comment]
Thanks for reporting. Please attach the RPP file in which this happens. If you think it doesn't depend on the particular project, attach the reaper.ini file instead.

**Comment by aeantipov** [comment]
I checked in an empty project.
It is related to the time signature. In 4/4 the tempo is correct.
![image](https://github.com/user-attachments/assets/cd424cf5-0b89-486d-82bf-4f83328ebc02)
If I switch it to 8/8, it is doubled, and the same happens in the click source properties. 
Playtime seems to be using the click source directly. It might be a "wont-fix".

[REAPER.ini.txt](https://github.com/user-attachments/files/17023062/REAPER.ini.txt)

**Comment by helgoboss** [comment]
Weird. Playtime uses the click source to power its metronome, true. But not to show the tempo. It just shows the tempo reported by REAPER itself at position zero. Does this happen in an empty project (no project template)? I'm not at home for a few days so I can't check.

**Comment by aeantipov** [comment]
It does. It's not critical or anything - the click works and you can play/record things, just strange to see the number off.
[playtime_tempo_test.zip](https://github.com/user-attachments/files/17029684/playtime_tempo_test.zip)

**Comment by helgoboss** [comment]
I could reproduce this with your project. Will look into it.
