### ISSUE TITLE
Console error messages since update to v2.16.8

### ISSUE THREAD

**Issue by daounandout** [helgoboss/helgobox#1205]
I get this console error every time I run an action that opens the first instrument FX on the selected track, but only when the instrument is the Spitfire Audio sampler (non-Kontakt). This happens whether there is an instance of Helgobox on the track or not.

This only started since the latest Helgobox update

--- cut ---
REAPER version:      7.22/OSX64
Module name:         Helgobox
Module version:      v2.16.8/x86_64 rev 5803cb (2024-09-14 18:57:33 UTC)
Module base address: 0x0
Module size:         -

Message: REAPER hwnd_info hwnd pointer was null

   0:        0x11e008b51 - <unknown>
   1:        0x11df616b9 - <unknown>
   2:        0x11e248393 - <unknown>
   3:        0x11e247ce2 - <unknown>
   4:        0x11e246679 - <unknown>
   5:        0x11e247a16 - <unknown>
   6:        0x11e30e672 - <unknown>
   7:        0x11e26dbfb - <unknown>
   8:        0x11e30e63c - <unknown>
   9:        0x11ceec654 - <unknown>
  10:        0x11d02bd8d - <unknown>
  11:        0x10e22cdbe - __Z17preTranslateAccelP3MSG
  12:        0x10de98003 - -[REAPERapp sendEvent:]
  13:     0x7ff81f4e46fe - <unknown>
  14:     0x7ff81f0b975d - <unknown>
  15:     0x7ff81f08d951 - <unknown>
  16:     0x7ff81bbf641f - <unknown>
--- cut ---

Mac OS Ventura 13.6.3

**Comment by helgoboss** [comment]
Thanks. I plan to fix this on September 23th. Until then, please downgrade.
