### ISSUE TITLE
MIDI loops do not follow project tempo changes

### ISSUE THREAD

**Issue by johnsamuelson** [helgoboss/helgobox#1211]
**Describe the bug**
Me again I'm afraid... this is a simple one to describe, record a MIDI loop at one tempo and then play through a project with tempo changes mapped out. The MIDI loop stays at the original / recorded tempo and doesn't move as the project tempo changes.

**To Reproduce**
Steps to reproduce the behaviour:
Record a 4 bar loop in a project playing back through the main Reaper timeline - then create a tempo change marker and play the same MIDI file back there... the tempo doesn't change to match the new one, so the clip gradually drifts out of time. It doesn't matter if the clip is quantized either, both ways it plays as the original tempo.

**Expected behaviour**
I would expect if the project tempo changed, the tempo of the MIDI file playback would change.. this is obviously one of the big bonuses of MIDI loops.

**Screenshots**

**Desktop (please complete the following information):**
2.16.8, Reaper 7.22.

**Comment by johnsamuelson** [comment]
(I would add - even with sync to project tempo turned on, Playtime doesn't seem to follow the master tempo - the display in the top left stays at the original / first tempo of the project and doesn't update / amend as tempo markers are passed.)

**Comment by helgoboss** [comment]
This is not a bug. Playtime doesn't support tempo envelopes at the moment, only ad-hoc tempo changes. There's a feature request though. Search in the discussion section for "tempo envelope" and vote for it.
