### ISSUE TITLE
UI Bug #1

### ISSUE THREAD

**Issue by JackOrez** [helgoboss/helgobox#1212]
helgoboss,

Thank you so much for the 'Background colors' option. [by the way I really like the dark mode in 'Pot Browser', any chance this could be added to Helgobox?]
I meant to respond earlier however I got busy documenting
some bugs.
OS = Win10, REAPER v7.22+dev0912

It appears as though v2.16.4 has introduced a rather nasty one. [I downgraded to 2.16.3 and the bug is not present]

Bug #1:
When using Computer Keyboard as a source the assigned key can sometimes pass through to REAPER.
Steps to reproduce:
1) First, in REAPER's action list set a key to an action (one that will have a visual effect when executed, such as Transport:Play)
2) Learn that same key as a source in Helgobox and set it as an 'Incremental Button' and 'Fire after timeout, keep firing (turbo).
3) Set target to a VST param.
4) Now if you hold the key you learned and Helgobox still has focus things may seem to work fine, but occasionally
the key will pass through and trigger the action it's assigned to in REAPER. I could'nt narrow that part down any furthur,
however if you click anywhere within REAPER so that Helgobox does not have focus and you hold the key, after about
1 sec. or so, both the action in REAPER and whatever you have assigned as target in Helgobox will both be firing.
This also happens regardless of the state of the plugin option 'Send all keyboard input to plug-in'.

**Comment by helgoboss** [comment]
Could reproduce this. Looks like the "key repeat event" is not properly "eaten" by ReaLearn. Fixing.
