### ISSUE TITLE
"Fire after timeout" does not appear to be functioning for sending MIDI messages

### ISSUE THREAD

**Issue by tjwrona** [helgoboss/helgobox#1231]
**Describe the bug**
I am trying to send 2 MIDI commands simultaneously to ReaLearn from Guitar Pro and then have ReaLearn map those MIDI commands to specific CC messages and send them out to my hardware device. Because my hardware device cannot handle both messages simultaneously I want to map one of them to use "fire after timeout" within ReaLearn, but the second I try to use that setting the command no longer seems to get sent to my hardware device (no matter how long the timeout is set to)

**To Reproduce**
I am trying to trigger these two ReaLearn mapping simultaneously:
![image](https://github.com/user-attachments/assets/0d5141c1-6e81-43b8-8bc0-b1a5a1d89e11)
![image](https://github.com/user-attachments/assets/0c299ae8-0d91-4232-8ffd-673ccc381b03)

If I set both to "fire on press" they seem to work (most of the time) the hardware device gets both commands, but sometimes it will discard one of them because it is receiving them both too quickly one after the other

**Expected behavior**
I would expect the "target" MIDI message to be sent out to the hardware device after the timeout (I tried setting the timeout to all different lengths, none of them seemed to work)

**Screenshots**
See screenshots in "To Reproduce" section

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version: 10.0.22631 Build 22631

**Additional context**
This is what it looks like from within Guitar Pro (2 notes being sent simultaneously)
![image](https://github.com/user-attachments/assets/a7cdbbc4-00fd-44ff-b7c5-70433d08e6ce)

**Comment by tjwrona** [comment]
Note, sending the first note as a "grace note" which happens slightly before the beat in Guitar Pro seems to work... so I will use this as a workaround for now. But ideally I would be able to send both notes simultaneously in Guitar Pro and have ReaLearn delay one of them by about 20 milliseconds to simplify my Guitar Pro charts.

**Comment by helgoboss** [comment]
I think "Fire after timeout" is not supported for real-time targets, yes. Would be a new feature.

**Comment by tjwrona** [comment]
Okay good to know, it is definitely confusing though. I will use the workaround for now because it is working great :)

**Comment by helgoboss** [comment]
I added an info about this limitation to the reference.
