### ISSUE TITLE
Reaper crashes (vanishes) when closing Playtime window

### ISSUE THREAD

**Issue by johnsamuelson** [helgoboss/helgobox#1233]
**Describe the bug**
Not sure why, but on my laptop on an older MacOS Playtime is crashing sometimes when closing the window. Crash report attached here....
[crash report.txt](https://github.com/user-attachments/files/17167159/crash.report.txt)

**Comment by helgoboss** [comment]
There's also this issue on macOS 10.14: https://github.com/helgoboss/helgobox/issues/1099. Not sure whether I can invest the effort to fix such issues. It sounds like a bunch of days effort to support old macOS versions. Let's see how often this comes up. If there's a substantial amount of users affected by this, I will have a look. Until then, I will probably raise the minimum supported macOS version on the Helgobox web page.

**Comment by helgoboss** [comment]
I declare this as duplicate of #1099.
