### ISSUE TITLE
 I noticed a too imperceptible blinking of the pads

### ISSUE THREAD

**Issue by Akognito** [helgoboss/helgobox#1267]
have a Launchpad pro mk3, when playing,
Uploading 20241014_194748.MP4…
, that is, an indication - as I understood it, it does not reach 0, but only reduces the brightness by a little - it is very difficult to navigate so, in Ableton the indication is better

**Comment by Akognito** [comment]
Uploading video_2024-10-14_19-55-14.mp4…

**Comment by Akognito** [comment]
https://github.com/user-attachments/assets/927afb1a-d160-4cc9-b578-47881652a17b

**Comment by helgoboss** [comment]
This will be fixed in 2.16.15 by always indicating playing clips as green (as in Ableton Live). I accidentally opened a new ticket for this: #1351
