### ISSUE TITLE
ring buffer too small for writing block

### ISSUE THREAD

**Issue by mrbelowski** [helgoboss/helgobox#1270]
Recording long (a 40+ seconds) item in Playtime triggers this error:

Module version:      v2.16.10/x86_64 rev 910f67 (2024-09-28 09:53:27 UTC)
Module path:         N:\REAPER (x64)\UserPlugins\FX\helgobox-x64.dll
Module base address: 0x7ffbd6fb0000
Module size:         0x27f8000

Message: called `Result::unwrap()` on an `Err` value: "ring buffer too small for writing block"

   0:     0x7ffbd8673a8b - VSTPluginMain
   1:     0x7ffbd8672972 - VSTPluginMain
   2:     0x7ffbd85e561b - VSTPluginMain
   3:     0x7ffbd888f1db - cpp_to_rust_PCM_source_Extended
   4:     0x7ffbd888efe6 - cpp_to_rust_PCM_source_Extended
   5:     0x7ffbd888d0df - cpp_to_rust_PCM_source_Extended
   6:     0x7ffbd888ebc6 - cpp_to_rust_PCM_source_Extended
   7:     0x7ffbd8b85984 - cpp_to_rust_PCM_source_Extended
   8:     0x7ffbd8b85e00 - cpp_to_rust_PCM_source_Extended
   9:     0x7ffbd84a2ee7 - VSTPluginMain
  10:     0x7ffbd84a2974 - VSTPluginMain
  11:     0x7ffbd84f4c32 - VSTPluginMain
  12:     0x7ffbd84ecc26 - VSTPluginMain
  13:     0x7ffbd84a1550 - VSTPluginMain
  14:     0x7ffbd7bffbf6 - VSTPluginMain
  15:     0x7ffbd7c018a5 - VSTPluginMain
  16:     0x7ffbd79636c3 - VSTPluginMain
  17:     0x7ffbd7b7d6ba - VSTPluginMain
  18:        0x14062bb35 - <unknown>
  19:        0x1400522fa - <unknown>
  20:     0x7ffc2b512bf7 - <unknown>
  21:     0x7ffc2b5134ee - <unknown>
  22:     0x7ffc2b51315b - <unknown>
  23:     0x7ffc2b52a352 - DllGetClassObject
  24:     0x7ffc4d957374 - BaseThreadInitThunk
  25:     0x7ffc4f0fcc91 - RtlUserThreadStart

I'm using Reaper version 7.22 (portable install, Windows 10) with a USB audio interface (Spark 2 with its ASIO driver set to 'safe mode'). I have 1 VST running (Midi drums) + 2 looped recordings (bass +rhythm). I'm adding a self-indulgent and not very good guitar solo, I get to the bit where I'm on my knees and nothing else exists in the world when this error happens.

I recently updated to Playtime 2.16.10 (yesterday). I've not seen this error before (I was using version 2.16.4 prior to this)

I see there's an existing closed issue referring to a similar error but the info on that suggests it's triggered by high sample rates - I'm recording 44kHz mono, 24bit

**Comment by helgoboss** [comment]
Hi. To which directory do you record the files? I suppose you have saved a project before recording, so it will probably record directly to the project directory. Is that directory on a somewhat slow disk maybe? Just asking to get more context. It's definitely a bug.

**Comment by mrbelowski** [comment]
the files go to a 1TB NVME SSD, which is about half full - I don't think the disk is likely to be the issue (but with Windows you can never be sure). My box is generally in pretty good health.

I doubled the ASIO driver buffer size and had another crack at it yesterday and it didn't crash. I guess it's possible that this is just an ASIO buffer under-run (or whatever it's called) but the error report makes it look like something breaking in the Playtime stack? I dunno :)

**Comment by helgoboss** [comment]
Thanks for the info. What were the different buffer sizes?

**Comment by mrbelowski** [comment]
it was 64 samples, it's now 128. TBH I don't recall what the default was, I shouldn't have fiddled with it

**Comment by helgoboss** [comment]
This error will be fixed in 2.18.0. Long recordings with low buffer sizes shouldn't be an issue anymore, unless the unhappy combination _slow file writing + super long recording_ occurs, which would eventually lead to exhaustion of memory.
