### ISSUE TITLE
ReaLearn: Custom actions or scripts picked with ReaLearn 2.16.3+ are saved incorrectly

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/helgobox#1272]
ReaLearn 2.16.3 (2024-08-24) introduced a bug: When using the action picker in target "REAPER: Invoke REAPER action" with a **script or custom action**, ReaLearn would save the numeric command ID. That's wrong because those numeric IDs can change at next REAPER start. It should save the permanent command name instead (a text).

**What happens if you are affected?**

- ReaLearn might confuse the actions with other ones after REAPER restarts! 

**If you picked script or custom actions with ReaLearn 2.16.3 - 2.16.10, you are affected by this bug! In this case, procede like this:**

1. Install Helgobox/ReaLearn 2.16.11+ (as soon as it is available)
2. Open all affected ReaLearn instances and pick the correct actions again. If it's a ReaLearn instance in a project (not on the monitoring FX chain), save the project explicitly.

**Comment by Ju-80** [comment]
Great, thank you :-)
