### ISSUE TITLE
ReaLearn: The management of multiple send and recieves does not work

### ISSUE THREAD

**Issue by seryoga9393** [helgoboss/helgobox#1286]
Hello, Benjamin! I think I've managed to create a Issue on GitHub :-)

Why can't I manage the receives and sends for a multichannel track using ReaLearn? All routing is displayed in the list, ReaLearn sees it, but it does not work as it should...
Relearn does not want to manage send and recevies on channels 3/4, 5/6, etc.
Learn only works with the first instance of send and recevies.

Windows 10 x64
Reaper 7.25
![1](https://github.com/user-attachments/assets/a074e11c-93ac-4c4a-950b-13aa94c800d5)

Alternative link: https://fastpic.org/fullview/124/2024/1006/_163e3dacc6fb4938bde6cae11fe1c0b6.gif.html

**Comment by helgoboss** [comment]
If you have multiple sends to the same destination track, the selector "Particular" is not the right choice. Please choose "At position" instead. I'll add this to the docs, thanks.

**Comment by seryoga9393** [comment]
Thank you very much! It's working! And why didn't I think of it myself...🤔
