### ISSUE TITLE
UPD: Include xdotool as dependency under manual install for OpenSuse.

### ISSUE THREAD

**Issue by Skrappjaw** [helgoboss/helgobox#1299]
**Describe the bug**
Linux install via ReaPack hangs at 80%
Progress Bar does not complete.
![image](https://github.com/user-attachments/assets/ebd46f61-e65c-4ae9-9057-37c7848868c8)

**To Reproduce**
Install ReaPack
Add Helgobox repo to ReaPack
Browse packaged
Select ReaLearn for install
click apply

**Desktop (please complete the following information):**
 - OS: Linux (OpenSuse Tumbleweed)

Attempted updated reaper and refreshing ReaPack. Wiped out ReaPack files from Reaper directories and started over. Same results.

**Comment by helgoboss** [comment]
Hmm. This is not really a Helgobox issue. In general, installation on Linux via ReaPack works. Just tried it. Maybe it just takes long? ReaPack unfortunately doesn't report progress per file. Helgobox contains some quite large files (30MB+).

**Comment by Skrappjaw** [comment]
I ended up selecting a lower version 2.16.10 and it installed. But now it wont show in the fx list. Auto scan is enabled and the .so file is in the UserPlugins directory.

**Comment by Skrappjaw** [comment]
Here is how reaper-vstplugins64.ini file reads. The Helgobox line looks like it has an incomplete listing....

graph_equalizer_x32_ms.so=808CDD68E51CDB01,1802844266,Graphic Equalizer x32 M/S (LSP VST)
graph_equalizer_x32_stereo.so=808CDD68E51CDB01,1853256548,Graphic Equalizer x32 Stereo (LSP VST)
**helgobox_x64.so=005CD85F752DDB01**
impulse_responses_mono.so=808CDD68E51CDB01,2004252532,Impulse Responses Mono (LSP VST)
impulse_responses_stereo.so=808CDD68E51CDB01,829122682,Impulse Responses Stereo (LSP VST)

**Comment by Skrappjaw** [comment]
I think I got it.... OpenSuse requires xdotool package. I made the test app from https://github.com/helgoboss/helgobox/issues/503 to find the missing package and searched Yast software for the package that provides what was missing.

Include xdotool as dependency under manual install for OpenSuse.

**Comment by helgoboss** [comment]
I added "sudo zypper install xdotool" to the installation instructions. Hope that's correct.
