### ISSUE TITLE
When mapping program change numbers, it usually doesn't make sense to rescale the program change numbers

### ISSUE THREAD

**Issue by ironirc** [helgoboss/helgobox#1302]
### Discussed in https://github.com/helgoboss/helgobox/discussions/1297

<div type='discussions-op-text'>

<sup>Originally posted by **ironirc** November  1, 2024</sup>
![Scherm­afbeelding 2024-11-01 om 14 58 05](https://github.com/user-attachments/assets/e6c852eb-7440-427c-b520-70b8c6de37ff)

Problem:
The target Max is dynamic - it depends on how many presets you have on the target Fx (Or Container in my case)

I see some possible solutions:
- Add a "No glue" option 
- Option to let "Glue - source max" follow the "Target max"
- Make target max value (an all others) available in Control transformation script

Or I'm missing the obvious solution, which would be the best outcome.</div>

**Comment by helgoboss** [comment]
I will close this issue because it's a not-yet-discussed improvement suggestion. The right place for this is the discussion section. Will reply there.
