### ISSUE TITLE
Can't find how to trigger next row/column or next slot via realearn

### ISSUE THREAD

**Issue by aeantipov** [helgoboss/helgobox#1342]
I am playing with a footswitch to go to next/previous row & column.
To do this I am trying to setup an action that goes to the **next** row or column from the one I'm now, so that I can navigate through the matrix with different clicks.
For this I'm trying to make use of "Dynamic" option for row/column/slot and going through https://docs.helgoboss.org/realearn/targets/playtime.html#dynamic-selector-variables 

However, when I try using `control_unit_row_index + 1` I simply get the second row, instead of repeating clicks moving me down the list of rows.

![image](https://github.com/user-attachments/assets/3cf16862-32fb-46ee-b9ee-608db0c3620f)

Not sure what I'm doing wrong though. 
Playtime is 2.16.4, Reaper is 7.25

**Comment by helgoboss** [comment]
You need to use mode "Incremental button" for that.

BTW, questions are better asked in "Discussions"

**Comment by aeantipov** [comment]
Thanks! Will follow.
