### ISSUE TITLE
PT2/ReaLearn MIDI trigger problems

### ISSUE THREAD

**Issue by sevenseas298** [helgoboss/helgobox#1358]
Windows 11
REAPER 7.28
PT2 version:  2.16.14

Problem A:
When a clip mapped to a MIDI trigger is triggered by a MIDI event, the Clip Inspector will switch focus to that clip.
This results in the Inspector Panel being unusable, as any other clip or column properties cannot be edited in the Inspector when MIDI triggers are received - the Inspector Panel will keep switching to the triggered clip.

Example:
1. Set Clip Slot 1/1 to trigger on note 48, velocity 68, channel 1
2. Create a looped 4 beat MIDI clip in Clip Slot 2/1 with a note 48, velocity 68, measure position 1.1, channel 1 routed to the PT2's  ReaLearn instance
3. Select Clip Slot 4/1 - the Inspector will display settings for this slot
4. Run Clip Slot 2/1
5. The Inspector will display  settings for Clip Slot 1/1 whenever Clip Slot 2/1 sends a trigger - and if the Inspector is displaying settings for the Matrix, any Column, or any other Clip Slot, the Inspector will switch to settings for Clip Slot 1/1
6. Now map Clip Slot 3/1 to the same note/velocity trigger as Clip Slot 1/1
7. Run Clip Slot 2/1
8. Whenever Clip Slot 2/1 sends a trigger, the Inspector will briefly display settings for Clip Slot 3/1 and then display settings for Clip Slot 1/1, regardless of what has been manually selected to display in the Inspector.
9. Now add an additional note/velocity trigger to MIDI Clip 2/1 at measure position 1.3 and map it to Clip Slot 4/1
10. Run Clip Slot 2/1
11. The Inspector will briefly display settings for Clip Slot 3/1, then Slot 1/1, then Slot 4/1 and then repeat the display sequence; if the Matrix or any other Clip Slot or Column is selected to display in the Inspector, the Inspector will revert to display of the triggered Slots.

This behavior is an impediment to workflow in the studio and impairs PT2's usefulness in performance settings.

Expected behavior:  The Inspector remains focused on what grid element the user has selected, regardless of what grid elements are being triggered.

Problem B:
Source values cannot be manually entered reliably in the Glue section of a ReaLearn mapping when MIDI triggers are received by ReaLearn.

Example:
1. Repeat steps 1-3 in Problem A example
2. Manually enter Min/Max values in the Glue section of a new or existing mapping.  They can be in "Source", "Target", or "For buttons (control only)".
3. Numeric entry, home/end keys, arrow keys, backspace key, shift-end, shift-home, and ctrl-A all work as expected
4. Now run the MIDI clip in Clip Slot 2/1 and try, for example, to manually enter a value in "Source Min" 
5. Every time a MIDI trigger is received in an active mapping, the cursor will move to the "home" position and if a new value is entered, the entry will revert to the original value and the cursor will return to the "home" position.

This problem occurs whenever a ReaLearn instance receives a MIDI trigger in an active mapping in any Unit of any Compartment and affects all mappings in the instance.  When a mapping being edited is disabled, the problem persists. The problem occurs with any source used and seems specific to the Glue section.  Sliders work as expected when MIDI triggers are received, but can be very difficult to adjust precisely.

Expected behavior:  Glue values can be manually entered normally when MIDI triggers are received by an active mapping. 

Thank you for ReaLearn and Playtime 2!

**Comment by helgoboss** [comment]
> Problem A: When a clip mapped to a MIDI trigger is triggered by a MIDI event, the Clip Inspector will switch focus to that clip. This results in the Inspector Panel being unusable, as any other clip or column properties cannot be edited in the Inspector when MIDI triggers are received - the Inspector Panel will keep switching to the triggered clip.

Disable "Matrix settings => Matrix playback settings => Activate slot on trigger"

> Problem B: Source values cannot be manually entered reliably in the Glue section of a ReaLearn mapping when MIDI triggers are received by ReaLearn.

I tried this on macOS and couldn't reproduce it. Maybe a Windows-only issue. I will look into it at some point.

**Comment by helgoboss** [comment]
> Problem B: Source values cannot be manually entered reliably in the Glue section of a ReaLearn mapping when MIDI triggers are received by ReaLearn.

I can't reproduce this, even on Windows. Can you attach a screen recording?

**Comment by sevenseas298** [comment]
Disabling "Activate slot on trigger" fixed both problems.

Thanks for your help.
