### ISSUE TITLE
Realearn and Playbox extension version 2.16.16 and above are crashing Reaper on startup on Mac Os 10.14.6

### ISSUE THREAD

**Issue by MCJ88k** [helgoboss/helgobox#1384]
Hello, 

The Realearn and Playbox extension version 2.16.16 and above are crashing Reaper on startup without exception on my Mac Os 10.14.6 system. I’ve reverted back to version 2.16.15 which works as expected. 

I fully understand if you don’t want to support this old OS anymore, but had to mention it. 
As always: thanks for this awesome piece of software, it makes Reaper so much more complete. 
  
To Reproduce
Install reaper_helgobox-x64.dylib 2.16.16 or above and start Reaper. 
 
My system: 
Mac OS 10.14.6
Reaper: 7.28

Crash Log: 

Crashed Thread:        0  reaper  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Application Specific Information:
/Users/Merl/Library/Application Support/REAPER/UserPlugins/FX/helgobox-x64.vst.dylib

Dyld Error Message:
  Symbol not found: _objc_opt_respondsToSelector
  Referenced from: /Users/USER/Library/Application Support/REAPER/*/helgobox-x64.vst.dylib
  Expected in: /usr/lib/libobjc.A.dylib

Thread 0 Crashed:: reaper  Dispatch queue: com.apple.main-thread
0   dyld                          	0x000000011750f3ba __abort_with_payload + 10
1   dyld                          	0x000000011750ebac abort_with_payload_wrapper_internal + 82
2   dyld                          	0x000000011750ebde abort_with_payload + 9
3   dyld                          	0x00000001174cea9d dyld::halt(char const*) + 343
4   dyld                          	0x00000001174cebc7 dyld::fastBindLazySymbol(ImageLoader**, unsigned long) + 167
5   libdyld.dylib                 	0x00007fff7d79332e dyld_stub_binder + 282
6   ???                           	0x000000011a02a300 0 + 4731347712
7   dyld                          	0x00000001174e2592 ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 506
8   dyld                          	0x00000001174e2798 ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 40
9   dyld                          	0x00000001174ddbea ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 362
10  dyld                          	0x00000001174dcd73 ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 133
11  dyld                          	0x00000001174dce05 ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 73
12  dyld                          	0x00000001174cfcb2 dyld::runInitializers(ImageLoader*) + 82
13  dyld                          	0x00000001174d93dc dlopen_internal + 607
14  libdyld.dylib                 	0x00007fff7d792d43 dlopen + 200
15  reaper_helgobox-x64.dylib     	0x0000000114ba3a82 libloading::safe::Library::new::h405e8ee51d27b8ad + 146
16  reaper_helgobox-x64.dylib     	0x0000000114ba35d9 reaper_helgobox::plugin_main::h977ebe7397effe20 + 1449
17  reaper_helgobox-x64.dylib     	0x0000000114bb9bfe reaper_low::util::bootstrap_extension_plugin::h6c2fec7f818c01cd + 158
18  reaper_helgobox-x64.dylib     	0x0000000114ba3024 ReaperPluginEntry + 36
19  com.cockos.reaper             	0x000000010a442a17 Plugins_Load(char const*) + 999
20  com.cockos.reaper             	0x000000010a8b4a1c MainProc(HWND__*, unsigned int, unsigned long, long) + 6844
21  com.cockos.reaper             	0x000000010a1df266 __localDlgProc(HWND__*, unsigned int, unsigned long, long) + 134
22  com.cockos.reaper             	0x000000010a6d0d31 -[REAPERSwell_hwnd initChild:Parent:dlgProc:Param:] + 1649
23  com.cockos.reaper             	0x000000010a6d7182 -[REAPERSwell_modelesswindow initModeless:Parent:dlgProc:Param:outputHwnd:forceStyles:] + 690
24  com.cockos.reaper             	0x000000010a6d88d0 SWELL_CreateDialog(SWELL_DialogResourceIndex*, char const*, HWND__*, long (*)(HWND__*, unsigned int, unsigned long, long), long) + 384
25  com.cockos.reaper             	0x000000010a1e03c3 __localizeDialog(void*, char const*, HWND__*, long (*)(HWND__*, unsigned int, unsigned long, long), long, int) + 355
26  com.cockos.reaper             	0x000000010a087457 macAppFinishInit(HWND__*, unsigned int, unsigned long, unsigned int) + 71
27  com.cockos.reaper             	0x000000010a0872f3 -[Controller applicationDidFinishLaunching:] + 1027
28  com.apple.CoreFoundation      	0x00007fff517178a2 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
29  com.apple.CoreFoundation      	0x00007fff5171781c ___CFXRegistrationPost_block_invoke + 63
30  com.apple.CoreFoundation      	0x00007fff51717786 _CFXRegistrationPost + 404
31  com.apple.CoreFoundation      	0x00007fff5171fc34 ___CFXNotificationPost_block_invoke + 87
32  com.apple.CoreFoundation      	0x00007fff51688424 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1642
33  com.apple.CoreFoundation      	0x00007fff516877d7 _CFXNotificationPost + 732
34  com.apple.Foundation          	0x00007fff5391333b -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
35  com.apple.AppKit              	0x00007fff4ecb06b0 -[NSApplication _postDidFinishNotification] + 312
36  com.apple.AppKit              	0x00007fff4ecb0003 -[NSApplication _sendFinishLaunchingNotification] + 208
37  com.apple.AppKit              	0x00007fff4ecae157 -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 552
38  com.apple.AppKit              	0x00007fff4ecadda7 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 688
39  com.apple.Foundation          	0x00007fff5395d0e0 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 286
40  com.apple.Foundation          	0x00007fff5395cf5d _NSAppleEventManagerGenericHandler + 102
41  com.apple.AE                  	0x00007fff528db397 aeDispatchAppleEvent(AEDesc const*, AEDesc*, unsigned int, unsigned char*) + 1815
42  com.apple.AE                  	0x00007fff528dac29 dispatchEventAndSendReply(AEDesc const*, AEDesc*) + 41
43  com.apple.AE                  	0x00007fff528dab01 aeProcessAppleEvent + 414
44  com.apple.HIToolbox           	0x00007fff5091b8b7 AEProcessAppleEvent + 54
45  com.apple.AppKit              	0x00007fff4ecaa1a9 _DPSNextEvent + 1935
46  com.apple.AppKit              	0x00007fff4eca8b77 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361
47  com.apple.AppKit              	0x00007fff4eca2c94 -[NSApplication run] + 699
48  com.apple.AppKit              	0x00007fff4ec921c0 NSApplicationMain + 777
49  com.cockos.reaper             	0x000000010a0301f4 start + 52

**Comment by helgoboss** [comment]
@MCJ88k Helgobox 2.18.0 will be compatible with older macOS versions again (ReaLearn only, not Playtime).

**Comment by MCJ88k** [comment]
Thanks a lot Benjamin. Really awesome.
