### ISSUE TITLE
Support non-main-section actions

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/helgobox#422]

**Comment by vonglan** [comment]
+1
would like to trigger midi quantization on recorded MIDI item

**Comment by helgoboss** [comment]
Workaround if it's urgent: ReaScript

**Comment by vonglan** [comment]
ah, of course. Thanks!

**Comment by tycho2112** [comment]
+1. would be really helpful to be able to control functions within media explorer and midi editor

**Comment by NickAllott** [comment]
This would be awesome to have! 
It would need to include a way to override other mappings if the midi editor etc is focused (similar to how Reaper assigned other section action shortcuts work).
Also, it would be terrific if "learn target" would respond to interactions with the non-main-sections as well. 😊

**Comment by tompad2** [comment]
+1

**Comment by helgoboss** [comment]
Working on this.

**Comment by tycho2112** [comment]
Thank you!

**Comment by helgoboss** [comment]
Small addition: Non-main actions currently don't support the invocation mode setting. No matter the invocation mode, it will always do "Trigger". In practice, this should not be relevant. I haven't found any "MIDI/CC style" MIDI editor or media explorer actions.
