### ISSUE TITLE
PT2E: can't record

### ISSUE THREAD

**Issue by vonglan** [helgoboss/helgobox#585]
As soon as I want to record MIDI data, I get an endless sequence of the internal error below.
If I just record without any incoming MIDI (haven't tried audio yet), there is no error, and the logged virtual messages look fine.

Pads are on an APC20. MIDI data for recording comes from OB6.

I attach the project. I think I cannot record the MIDI from the APC20 without messing other things up.
Ah yes, I could record it without ReaLearn active, if that is of any help.

-- cut ---
REAPER version:      6.56/macOS-arm64
Module name:         ReaLearn
Module version:      v2.13.0-pre.4/aarch64 rev c31d4f (2022-05-12 14:36:57 UTC)
Module base address: -
Module size:         -

Message: called `Option::unwrap()` on a `None` value

   0:        0x121584cf8 - <unknown>
   1:        0x121595cc4 - <unknown>
   2:        0x12148a0f4 - <unknown>
   3:        0x1215c5810 - <unknown>
   4:        0x1215c552c - <unknown>
   5:        0x1215c29ec - <unknown>
   6:        0x1215c52bc - <unknown>
   7:        0x121626a70 - <unknown>
   8:        0x1216269f4 - <unknown>
   9:        0x12140ed18 - <unknown>
  10:        0x1213ed6b4 - <unknown>
  11:        0x1213e069c - <unknown>
  12:        0x120e4413c - <unknown>
  13:        0x120f10d28 - <unknown>
  14:        0x120e4502c - <unknown>
  15:        0x120dae918 - <unknown>
  16:        0x121107260 - <unknown>
  17:        0x104b53e88 - __Z21audiostream_onsamplesPPdiS0_iii
  18:        0x104bb8f74 - __ZN23audioStreamer_CoreAudio9onsamplesEPK15AudioBufferListPS0_
  19:        0x104bb9774 - __ZL8caIOprocjPK14AudioTimeStampPK15AudioBufferListS1_PS2_S1_Pv
  20:        0x19e123138 - <unknown>
  21:        0x19e29c388 - <unknown>
  22:        0x19c797878 - _pthread_jit_write_protect_np
--- cut --
[clip-engine-basic.RPP.zip](https://github.com/helgoboss/realearn/files/8827664/clip-engine-basic.RPP.zip)
-

**Comment by vonglan** [comment]
With pre.6, recording works once, then with the second recording attempt, I get an internal error again. It looks very similar:

--- cut ---
REAPER version:      6.60/macOS-arm64
Module name:         ReaLearn
Module version:      v2.13.0-pre.6/aarch64 rev 70947c (2022-06-12 13:27:24 UTC)
Module base address: -
Module size:         -

Message: called `Option::unwrap()` on a `None` value

   0:        0x1231bfa24 - <unknown>
   1:        0x1231cf8c8 - <unknown>
   2:        0x1230cbe1c - <unknown>
   3:        0x123202b08 - <unknown>
   4:        0x123202928 - <unknown>
   5:        0x123200f1c - <unknown>
   6:        0x1232026b8 - <unknown>
   7:        0x123263764 - <unknown>
   8:        0x123263684 - <unknown>
   9:        0x122fae2a8 - <unknown>
  10:        0x122f918c8 - <unknown>
  11:        0x122f7a6d8 - <unknown>
  12:        0x122b3546c - <unknown>
  13:        0x122b570bc - <unknown>
  14:        0x122b36238 - <unknown>
  15:        0x122a84cf0 - <unknown>
  16:        0x122cf25f8 - <unknown>
  17:        0x1030f5fc8 - __Z21audiostream_onsamplesPPdiS0_iii
  18:        0x10315b2a4 - __ZN23audioStreamer_CoreAudio9onsamplesEPK15AudioBufferListPS0_
  19:        0x10315bb54 - __ZL8caIOprocjPK14AudioTimeStampPK15AudioBufferListS1_PS2_S1_Pv
  20:        0x19415f138 - <unknown>
  21:        0x1942d8388 - <unknown>
  22:        0x1927d3878 - _pthread_jit_write_protect_np
--- cut ---

**Comment by vonglan** [comment]
It also seems that the internal errors do not occur in a rapid, endless loop (2 per second), but much slower (1 per 2 seconds)

**Comment by vonglan** [comment]
that’s ok for me (it’s in alpha test)

just wanted to inform you

**Comment by vonglan** [comment]
fyi: 
Still occurs with pre.11.
I once managed to record 3 slots, before the problem occurred.
I could try to find out any regularities, how to reproduce it, if that is of any use.

**Comment by helgoboss** [comment]
FYI, I'm not working on that ATM. I'm sure this error will pop up right in my face when I start working on it again. More busy with the GUI and ReaLearn tutorials right now.

**Comment by vonglan** [comment]
ok, thanks for the info!

**Comment by vonglan** [comment]
Solved now
