### ISSUE TITLE
Playtime doesn't auto-detect Novation Launchpad Pro with family ID "00 FF"

### ISSUE THREAD

**Issue by ndbroadbent** [helgoboss/helgobox#939]
Hello! I've bought a license for Playtime 2 and I would love to use my Novation Launchpad Pro MK2 to control it. I'm struggling to figure out how to get it working.

The ReaLearn => Controllers page is blank in the settings:

<img width="807" alt="Screenshot 2024-07-22 at 4 52 06 PM" src="https://github.com/user-attachments/assets/79b454b6-af34-4917-ac6b-61ba37bbfead">

I found the "Launchpad Pro mk2 - Live mode" controller preset in the Helgobox / ReaLearn plugin settings, but this doesn't seem to do anything:

<img width="988" alt="Screenshot 2024-07-22 at 4 54 17 PM" src="https://github.com/user-attachments/assets/40f51543-281c-4e81-b4bf-db1c69774a42">

Is there a way to get the buttons and LED lights on my Launchpad Pro MK2 in sync with Playtime 2? Thanks!

Is my controller supposed to show up automatically in the ReaLearn => Controllers page?

Here's a screenshot of my MIDI hardware settings in REAPER:

<img width="1283" alt="Screenshot 2024-07-22 at 5 03 11 PM" src="https://github.com/user-attachments/assets/86267176-53bd-4a6e-8b8c-83e5c6a40df1">

**Comment by helgoboss** [comment]
Hi, this controller should detected by Playtime 2 automatically. For this to work, you need to do this:

1. Set input back to `FX input` and output to `None` (the auto detection is only used if you don't already use the controller explicitly in ReaLearn).
2. Disconnect the controller for a few secs
3. Connect it again (the auto detection currently only reacts to newly connected controllers)

I'm closing this now but feel free to comment to this ticket if this doesn't work for you!

That the "Controllers" panel is completely empty if no controller is set up yet, is bug #940.

**Comment by ndbroadbent** [comment]
Hi @helgoboss, thanks for your help! Unfortunately these steps didn't work for me.

I've tried unplugging the USB cable for a few seconds and plugging it back in. I also tried turning it off and then turning it back on, then selecting "Live" mode.

I'm using a Apple MacBook M2 Pro. I can also confirm that the launchpad works fine normally and can be used to trigger MIDI events for Battery 4 drum kits, etc. I'm not sure if this is relevant, but I've connected the launchpad via a 4-port USB hub, and it's not directly plugged into the laptop's USB-C port.

**Comment by ndbroadbent** [comment]
I was taking a look at the available controller options in Ableton Live Lite, and I'm a bit confused about the "MK2" -

<img width="317" alt="Screenshot 2024-07-23 at 12 39 53 PM" src="https://github.com/user-attachments/assets/825afe18-2c3d-4c79-b4d8-5454642e0cb5">

I think I might just have a "Launchpad Pro" (not a "Launchpad MK2"). Thanks!

**Comment by helgoboss** [comment]
I think you have the correct Launchpad, I might have named it wrong (as there is no Launchpad Pro Mk1).

Okay, now we need to do some analysis. Could you please do the following:

1. Quit REAPER
2. Disconnect your Launchpad
3. Open the macOS Terminal app
4. Enter the following command line: `HELGOBOX_LOG=debug /Applications/REAPER.app/Contents/MacOS/REAPER > $HOME/Downloads/helgobox.log` (this should start REAPER)
5. Start Playtime within REAPER
6. Connect your Launchpad and wait a few seconds
7. Quite REAPER
8. Reply within this issue, attaching the file "helgobox.log" in your Downloads directory

Thanks!

**Comment by ndbroadbent** [comment]
Thanks for the instructions! Here's the log file:

[helgobox.log](https://github.com/user-attachments/files/16349178/helgobox.log)


I think I might have found the relevant lines:

```

  [2m2024-07-23T13:00:10.860161Z[0m [32m INFO[0m [1;32mhelgobox::infrastructure::plugin::backbone_shell[0m[32m: [1;32mmsg[0m[32m: "Input not yet used. Finding matching controller preset...", [1;32mout_port_name[0m[32m: Focusrite A.E. Ltd - Launchpad Pro 16 - Live Port[0m
    [2;3mat[0m main/src/infrastructure/plugin/backbone_shell.rs:2665

  [2m2024-07-23T13:00:10.860171Z[0m [33m WARN[0m [1;33mhelgobox::infrastructure::plugin::backbone_shell[0m[33m: [1;33mmsg[0m[33m: "Couldn't automatically create controller for device", [1;33mout_dev_id[0m[33m: 7, [1;33merror[0m[33m: no controller preset matching device[0m
    [2;3mat[0m main/src/infrastructure/plugin/backbone_shell.rs:2977
```

**Comment by helgoboss** [comment]
Thanks. It looks the "identity reply" of your device (as a response to ReaLearn's MIDI device inquiry) is a bit different from my Launchpad Pro:

F0 7E 00 06 02 00 20 29 51 00 **0F 00** 00 01 05 04 F7 // reply from your device
F0 7E 00 06 02 00 20 29 51 00 **00 00** * F7 // expected pattern

The difference is in the device family member code, indicating that your device might be a different one. The [Launchpad Pro Programmers Reference Guide](https://fael-downloads-prod.focusrite.com/customer/prod/s3fs-public/downloads/Launchpad%20Pro%20Programmers%20Reference%20Guide%201.01.pdf) page 19 has "00 00" as family code, not "0F 00". I'm referring to this product: https://downloads.novationmusic.com/novation/launchpad-mk2/launchpad-pro

Novation also has this pretty cool web-based tool Components https://novationmusic.com/components, it should show the name of your device when it's connected. Could you try that?

**Comment by ndbroadbent** [comment]
Hi @helgoboss, ah it looks like I have an older Launchpad Pro (MK1) that is not supported by the Components tool.

![SCR-20240724-kkcq](https://github.com/user-attachments/assets/482de28b-27a4-4916-a72b-4376e2b8bae1)

I also downloaded the updater tool and updated the firmware from 154 to 182:

<img width="592" alt="image" src="https://github.com/user-attachments/assets/776f3876-fed6-4332-9da9-0bcc3bab899c">

I ran the instructions above again with the updated firmware (182), and have attached the new log file: [helgobox.log](https://github.com/user-attachments/files/16355217/helgobox.log)

**Comment by ndbroadbent** [comment]
I tried plugging the launchpad pro directly into my laptop (instead of via a USB hub), but that didn't change the identity reply:

```

  [2m2024-07-23T23:36:15.468110Z[0m [34mDEBUG[0m [1;34mhelgobox::domain::audio_hook[0m[34m: [1;34mmsg[0m[34m: "Sending MIDI device inquiry...", [1;34moutput_dev_id[0m[34m: MidiOutputDeviceId(7)[0m
    [2;3mat[0m main/src/domain/audio_hook.rs:440

  [2m2024-07-23T23:36:15.479719Z[0m [34mDEBUG[0m [1;34mhelgobox::domain::audio_hook[0m[34m: [1;34mmsg[0m[34m: "Received MIDI device identity reply", [1;34mreply[0m[34m: RequestMidiDeviceIdentityReply { input_device_id: MidiInputDeviceId(8), device_inquiry_reply: MidiDeviceInquiryReply { message: [240, 126, 0, 6, 2, 0, 32, 41, 81, 0, 15, 0, 0, 1, 8, 2, 247] } }[0m
    [2;3mat[0m main/src/domain/audio_hook.rs:620

  [2m2024-07-23T23:36:15.487069Z[0m [34mDEBUG[0m [1;34mhelgobox::infrastructure::plugin::backbone_shell[0m[34m: [1;34mmsg[0m[34m: "Resetting MIDI output and input devices to previous state..."[0m
    [2;3mat[0m main/src/infrastructure/plugin/backbone_shell.rs:2633

  [2m2024-07-23T23:36:15.487487Z[0m [32m INFO[0m [1;32mhelgobox::infrastructure::plugin::backbone_shell[0m[32m: [1;32mmsg[0m[32m: "Received identity reply from MIDI device", [1;32mout_dev_id[0m[32m: 7, [1;32min_dev_id[0m[32m: 8, [1;32mreply[0m[32m: F0 7E 00 06 02 00 20 29 51 00 0F 00 00 01 08 02 F7[0m
    [2;3mat[0m main/src/infrastructure/plugin/backbone_shell.rs:2640

  [2m2024-07-23T23:36:15.487515Z[0m [34mDEBUG[0m [1;34mhelgobox::infrastructure::plugin::backbone_shell[0m[34m: [1;34mmsg[0m[34m: "Check if input used already used by existing controller..."[0m
    [2;3mat[0m main/src/infrastructure/plugin/backbone_shell.rs:2647

  [2m2024-07-23T23:36:15.487522Z[0m [32m INFO[0m [1;32mhelgobox::infrastructure::plugin::backbone_shell[0m[32m: [1;32mmsg[0m[32m: "Input not yet used. Finding matching controller preset...", [1;32mout_port_name[0m[32m: Focusrite A.E. Ltd - Launchpad Pro 16 - Live Port[0m
    [2;3mat[0m main/src/infrastructure/plugin/backbone_shell.rs:2665

  [2m2024-07-23T23:36:15.487531Z[0m [33m WARN[0m [1;33mhelgobox::infrastructure::plugin::backbone_shell[0m[33m: [1;33mmsg[0m[33m: "Couldn't automatically create controller for device", [1;33mout_dev_id[0m[33m: 7, [1;33merror[0m[33m: no controller preset matching device[0m
    [2;3mat[0m main/src/infrastructure/plugin/backbone_shell.rs:2977
```

**Comment by ndbroadbent** [comment]
I'm in New Zealand, so maybe they use "00 0F" for devices sold in Australia / NZ?

**Comment by helgoboss** [comment]
I just tried my own Launchpad Pro with Components and it gives the same screen as you and is named "Launchpad Pro [MK1]". A bit confusing because the first Launchpad Pro is listed under the "Launchpad MK2" category on the Novation website: https://downloads.novationmusic.com/novation/launchpad-mk2

Mysterious how the family ID is different. However, the devices look the same, have the same name, so I guess my official preset would work with your device. Could you try this in your Playtime project (it's the most manual way to use the presets):

1. Open the plug-in
2. Set both input and output to the Launchpad Pro Live Port
3. Go to the controller compartment and choose preset "Launchpad Pro mk2 - Live mode"
4. Go to the main compartment and choose preset "Launchpad Pro mk2 - Playtime"

That should make things work for this particular project. If you confirm it works, I will adjust the MIDI identity pattern for the next version so that it covers your family ID as well. Then it should be auto-detected in the next version.

**Comment by ndbroadbent** [comment]
Awesome, it's working perfectly now! Thanks very much!

**Comment by helgoboss** [comment]
Okay, then I will relax the detection so that your device is included automatically in the future.
