### ISSUE TITLE
Playtime: Recording MIDI from another track 

### ISSUE THREAD

**Issue by Akognito** [helgoboss/helgobox#947]
I have controllers that work through scripts (Push1 and 2), and I can't select them in Playtime2 - are they not in the list?  And if it were possible to send midi and record from another track, then they would work in Playtime2, and in general this is a common function and should be supported accordingly

**Comment by helgoboss** [comment]
Please describe in more detail why you need this, what's your goal. Plus, I don't understand what Push 1 and Push 2 have to do with "recording MIDI from another track".

**Comment by Akognito** [comment]
I can redirect from another midi track with a push that works through the
Mossa script, so Playtime2 does not define it, but it will bypass this

пн, 22 июл. 2024 г., 19:32 Benjamin Klum ***@***.***>:

**Comment by Akognito** [comment]
And if I turn on the Push button, it loses all functionality

вт, 23 июл. 2024 г., 00:51 AkognitO ***@***.***>:

**Comment by Akognito** [comment]
And if I include Push directly, it loses all functionality

вт, 23 июл. 2024 г., 00:54 AkognitO ***@***.***>:

**Comment by Akognito** [comment]
Также вы можете отправить в Playtime2 фрагмент из трека готовой
MIDI-партии, включив функцию записи и записав фрагмент, который можно будет
использовать в скрипте.

вт, 23 июл. 2024 г., 00:56 AkognitO ***@***.***>:

**Comment by Akognito** [comment]
You can also send a fragment from the track of the finished MIDI part to
Playtime2 by switching on the recording function and recording a fragment
that you can use in the script.

вт, 23 июл. 2024 г., 01:10 AkognitO ***@***.***>:

**Comment by helgoboss** [comment]
Honestly, I have big struggles understanding what you wrote. Here's my guess:

- You use the DrivenByMoss extension in order to use Push with REAPER
- You want to record MIDI notes via Push into Playtime as a clip (= using Push as a MIDI keyboard)

1. Is this correct?
2. If yes, have you tried setting "Push" as MIDI track input for the Playtime column track? Why doesn't it work?

**Comment by Akognito** [comment]
When you use DrivenByMoss script, the controller can't be enabled in
Reaper, so it's not in Playtime either, although it is visible on Tracks of
course


вт, 23 июл. 2024 г., 11:56 Benjamin Klum ***@***.***>:

**Comment by helgoboss** [comment]
> When you use DrivenByMoss script, the controller can't be enabled in Reaper, so it's not in Playtime either

Okay, so it seems DrivenByMoss needs exclusive access to the Push MIDI device.

> although it is visible on Tracks of course

Can you post a screenshot of this? I don't know why it would be visible on tracks if you can't even enable the device within REAPER.

**Comment by Akognito** [comment]
[image: image.png]

вт, 23 июл. 2024 г. в 13:10, Benjamin Klum ***@***.***>:

**Comment by helgoboss** [comment]
Okay, I watched the video that you sent me via email:

- The MIDI input device "Ableton Push" is disabled in REAPER because DrivenByMoss needs exclusive access to it.
- The MIDI input device "MIDIIN2 (Ableton Push)" is enabled in REAPER.
- What you see in the track input menu is the "MIDIIN2 (Ableton Push)" device.

What is that MIDIIN2 device? Does Push use it to play normal MIDI notes?

**Comment by Akognito** [comment]
Это же вход и выход миди

вт, 23 июл. 2024 г. в 13:44, Benjamin Klum ***@***.***>:

**Comment by Akognito** [comment]
That's the same input and output of midi, for feedback and so on

вт, 23 июл. 2024 г. в 13:50, AkognitO ***@***.***>:

**Comment by helgoboss** [comment]
Can you record MIDI items with "MIDIIN2 (Ableton Push)" in REAPER itself (not in Playtime!)?

**Comment by Akognito** [comment]
[image: image.png]

вт, 23 июл. 2024 г. в 13:50, AkognitO ***@***.***>:

**Comment by Akognito** [comment]
yes

вт, 23 июл. 2024 г. в 13:52, Benjamin Klum ***@***.***>:

**Comment by helgoboss** [comment]
Then it should also work for recording MIDI clips in Playtime. You simply set it as MIDI input on the Playtime Column track. Doesn't that work?

**Comment by Akognito** [comment]
No, he's not on the list.
вт, 23 июл. 2024 г. в 13:57, Benjamin Klum ***@***.***>:

**Comment by helgoboss** [comment]
Can you post a screenshot of the MIDI input device list in Playtime?

BTW, you can also use the REAPER track input menu to select the MIDI device there.

**Comment by Akognito** [comment]
Sorry, my settings are wrong in midi devices, in the track setup there is
no Push controller, respectively Playtime too - it transfers data directly
from the crypt, it turns out[image: image.png]
[image: image.png]


вт, 23 июл. 2024 г. в 14:06, Benjamin Klum ***@***.***>:

**Comment by helgoboss** [comment]
I can't see the images. What is "crypt"?

**Comment by Akognito** [comment]
[image: image.png]


вт, 23 июл. 2024 г. в 15:48, Benjamin Klum ***@***.***>:

**Comment by Akognito** [comment]
script


вт, 23 июл. 2024 г. в 15:50, AkognitO ***@***.***>:

**Comment by Akognito** [comment]
вт, 23 июл. 2024 г. в 15:52, AkognitO ***@***.***>:

**Comment by helgoboss** [comment]
Well, if no Push MIDI device is usable in REAPER itself because DrivenByMoss needs exclusive access to it, there's not much I can do. Are you sure that MIDIIN2 is occupied by DrivenByMoss and not usable? 

BTW, I still can't see the image. Usually you just need to copy the image using Ctrl+C and press Ctrl+V here in the discussion.

**Comment by Akognito** [comment]
I even attached the archive to you by sending it and there's a photo.


вт, 23 июл. 2024 г. в 16:22, Benjamin Klum ***@***.***>:

**Comment by Akognito** [comment]
I get around this by using a virtual midi Reaper (configuring it to see
midi from the controller) - and selecting it in Playtime


вт, 23 июл. 2024 г. в 16:28, AkognitO ***@***.***>:

**Comment by helgoboss** [comment]
> I even attached the archive to you by sending it and there's a photo.

It doesn't arrive here. Check https://github.com/helgoboss/helgobox/issues/947 to see what I mean. Better don't respond via email but in the issue track directly, maybe it works then.

> I get around this by using a virtual midi Reaper (configuring it to see
midi from the controller) - and selecting it in Playtime

Okay. Then when you select this in Playtime as input for a track, can you record the MIDI to a clip? Is your problem resolved now?

**Comment by Akognito** [comment]
When I use Reaper's virtual midi to send - it works like this


вт, 23 июл. 2024 г. в 16:48, Benjamin Klum ***@***.***>:

**Comment by Akognito** [comment]
works when using virtual midi


вт, 23 июл. 2024 г. в 18:50, AkognitO ***@***.***>:

**Comment by helgoboss** [comment]
Checking again: Is your issue resolved now? If yes, I'm going to close this issue.
