### ISSUE TITLE
Playtime: When having PDC, first MIDI notes may be skipped after recording loop and playing it back again

### ISSUE THREAD

**Issue by helgoboss** [helgoboss/helgobox#968]

**Comment by atencion** [comment]
Yes, and also happens that when i press play in reaper arrangemenent many audio clips dont trigger in playtime the first time. They do in the second loop. Should i put that in a different issue? Thanks!
 (Max, from Argentina)

**Comment by helgoboss** [comment]
Yes, please open a different issue. It's also related to PDC but it may need to be handled differently.

**Comment by helgoboss** [comment]
Doesn't work yet with tempo detection recordings.

**Comment by atencion** [comment]
Great it`s done! 
Thanks!

This all hasn`t been released yet, right? 
I`ve seen theres a new milestone  2.16.1 with 90% done. That means one more and we get a new update?
YES!! 
THanks so much for your hard work.

**Comment by helgoboss** [comment]
That's right. I hope to push 2.16.1 during the next days.
