### ISSUE TITLE
Some audio clips in Playtime don`t trigger when I play Reaper Arrangement

### ISSUE THREAD

**Issue by atencion** [helgoboss/helgobox#989]
**Describe the bug**
When I press PLAY in reaper arrangemenent I can`t hear the sound of many audio clips that are triggered in playtime the first time. They do in the second loop.

**To Reproduce**
1. Close Playtime Window where all my audio clips are in different channels.
2. Click PLAY on Reaper Arrangement
3. Audio clips in arrangement play normally and PLaytime also syncs with Reaper.
4. Some Playime clips play, other dont in Playtime

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Ive seen similar behaviour with other VSTs that have an internal sequencer like XO that won`t play unless i open the VST at least once in the session. May help to solve the problem, not sure.

**Comment by helgoboss** [comment]
Can you add a video/screencast of this?

**Comment by helgoboss** [comment]
I think this might in fact be related to #1000 (which is fixed in upcoming 2.16.1). There's a theoretical possibility that this could have delayed audio to the next bar. I'll just close this for now as fixed. If it reoccurs in 2.16.1, feel free to comment.
